### ISSUE TITLE
Error while execute npm run sonarqube-scanner-node command

### ISSUE THREAD

**Issue by pateljayg** [mp-architech/sonarqube-scanner#1]
**Error while execute npm run sonarqube-scanner-node command**

E:\...>npm run sonarqube-scanner-node

[17:04:46] Executing sonarqube-scanner ...\
node_modules\sonarqube-scanner-node\dist\sonar-scanner-3.0.3.778\bin\sonar-scann
er\.bat
child_process.js:504
    throw err;
    ^

Error: spawnSync ...\git\zara-cargo-mobile\node_modules\sonarqube
-scanner-node\dist\sonar-scanner-3.0.3.778\bin\sonar-scanner\.bat ENOENT
    at exports._errnoException (util.js:1018:11)
    at spawnSync (child_process.js:459:20)
    at execFileSync (child_process.js:496:13)
    at Object.<anonymous> (...\git\zara-cargo-mobile\node_modules
\sonarqube-scanner-node\src\index.js:18:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "sonarqube"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

**I also Test sonarqube-scanner-node in  Browser from https://www.npmjs.com/package/sonarqube-scanner-node . It also not working.** 

Error Stack Trace Viewer 
Error: spawnSync /app/available_modules/1500637668000/sonarqube-scanner-node/dist/sonar-scanner-3.0.3.778/bin/sonar-scanner ENOENT
at util._errnoException in core util.js — line 1022
at child_process.spawnSync in core child_process.js — line 461
at child_process.execFileSync in core child_process.js — line 498
in sonarqube-scanner-node/src/index.js — line 18
node.js startup…

Please help me to solve this problem.

**Comment by mp-architech** [comment]
@pateljayg: I just fixed issue for win 10 but it looked different than yours, update package to version 0.0.7 and see if that fixes your issue.
