### ISSUE TITLE
Could not initialize NSS

### ISSUE THREAD

**Issue by pankajjangir777** [mp-architech/sonarqube-scanner#6]
ERROR: Error during SonarQube Scanner execution
ERROR: null
ERROR: Caused by: Could not initialize NSS
ERROR: Caused by: /usr/lib/libnss3.so
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.

**Comment by mp-architech** [comment]
@pankajjangir777 : you will have to manually install NSS on your OS before running scanner...
