### ISSUE TITLE
Update default  sonar-scanner-cli reference

### ISSUE THREAD

**Issue by ianwilliams1** [mp-architech/sonarqube-scanner#8]
The current default  SONAR_SCANNER_CLI_VERSION is sonar-scanner-cli:3.2.0.1227, from May 2018.

Current [release](https://jira.sonarsource.com/secure/ConfigureReleaseNote.jspa?projectId=11230) is [4.5.0.2216](https://github.com/SonarSource/sonar-scanner-cli/releases). 

Recommend updating to a more recent version, concurrent with the [LTS release](https://www.sonarqube.org/downloads/).

**Comment by samigt** [comment]
@mp-architech  please avoid using third party mirrors` npm.taobao.org`

**Comment by mp-architech** [comment]
@ianwilliams1, Updated cli version to latest in 0.0.11 version
@samigt, third party mirror urls are just reference if anyone wants to use different mirror, package uses official mirror only.
